- id: remove-consecutive-blank-lines
  name: remove any consecutive blank lines
  description: removes any consecutive blank lines in a file
  entry: remove-consecutive-blank-lines
  language: python
- id: check-process-script-syntax
  name: check the syntax of any script blocks
  description: checks that the contents of any script blocks in process definitions
  entry: check-process-script-syntax
  language: python
- id: detect-single-quote-script-blocks
  name: detect single quote delimited script blocks
  description: detects any script blocks that have been delimited by triple single quotes
  entry: detect-single-quote-script-blocks
  language: python
- id: detect-non-bash-shebangs
  name: detect non-bash shebangs in script blocks
  description: detects any script blocks that have a non-bash shebang (if they have a shebang)
  entry: detect-non-bash-shebangs
  language: python
- id: check-process-script-length
  name: check length of any script blocks
  description: checks that the length of any script blocks in process definitions do not exceed the required length
  entry: check-process-script-length
  language: python
  args: [--max_block_length=20]
