- id: detect-consecutive-blank-lines
  name: detect any consecutive blank lines
  description: detects any cases of two or more consecutive blank lines in a file
  entry: detect-consecutive-blank-lines
  language: python
- id: check-process-script-syntax
  name: check the syntax of any script blocks
  description: checks that the contents of any script blocks in process definitions
  entry: check-process-script-syntax
  language: python
